Settings:
  Prefix: '' #The prefix before the messages CrazyEnvoys sends.
  Toggle-Metrics: true #Turn on and off if your server stats are sent to https://bstats.org/plugin/bukkit/CrazyEnvoy.
  Falling-Block-Toggle: true #Toggle if it spawns a falling block or if the crates just appear.
  Falling-Block: 'BEACON' #The block that will be falling.
  Fall-Height: 15 #How high the falling blocks spawn.
  Max-Crate-Toggle: true #If true then only a specified amount of crates will spawn and if false then all crates will spawn.
  Max-Crates: 20 #The max amount of crates that will spawn.
  Random-Locations: false #If true you will need to make sure to set the center location.
  Max-Radius: 300 #The maximum distance the crates will fall from the center.
  Min-Radius: 20 #The minimum distance from the middle the crates will fall from.
  Envoy-Run-Time: '10m' #The amount of time the crazyenvoy event will go for.
  Envoy-Timer-Toggle: true #If the crazyenvoy will happen on an interval. If false the only wait it will start is if its started with the command or flare.
  Envoy-Cooldown-Toggle: true #Toggle if it uses a cooldown or a specified time of the day.
  Envoy-Cooldown: '4h' #The time till the crazyenvoy event will happen again.
  Envoy-Time: '2:00 AM' #A specified time of the day that an crazyenvoy will happen. Please use 1-12 for hours and 0-59 for minutes.
  Minimum-Players-Toggle: true #When the crazyenvoy is about to start toggle if there needs to be a minimum amount of players. (Does not affect flares)
  Minimum-Flare-Toggle: true #Toggle if using a flare has to meet the minimum players requirement. Minimum-Players-Toggle must be true for this to work.
  Minimum-Players: 6 #The minimum amount of players needed to start the crazyenvoy.
  Broadcast-Crate-Pick-Up: true #Toggle if when a player gets a crate if it broadcasts the message.
  Crate-Collect-Cooldown: #If when a player collects a crate if they have to wait to collect another.
    Toggle: true #Toggle this option on and off.
    Time: '15s' #The time till they have to wait.
  World-Messages:
    Toggle: false #Toggle if the broadcast messages are only in a specific worlds.
    Worlds: #The worlds you wish to have the messages only show up in.
      - 'world'
  Envoy-Warnings: #The times that will make the warning messages.
    - '30m'
    - '15m'
    - '10m'
    - '1m'
    - '30s'
    - '20s'
    - '10s'
    - '5s'
    - '3s'
    - '1s'
  Flares: #Options about flares. Players need the crazyenvoy.flare.use permission to use the flares.
    Item: 'REDSTONE_TORCH' #The time the flares are.
    Name: '&c&lSvětlice' #The name of the flare.
    Lore: #The lore of the flare.
      - '&fKlikněte &bpravým &fpro přivolání'
      - '&bAir-Dropu&f.'
    World-Guard: #The options for when using world guard regions to make flares work only in those regions.
      Toggle: false #If they have to use flares in specified regions.
      Regions: #The name of the regions you can use flares in.
        - 'WarZone'